"""empty message

Revision ID: 2452d32ad6e7
Revises: cf7a7f876d4c
Create Date: 2020-05-01 19:08:59.011173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2452d32ad6e7'
down_revision = 'cf7a7f876d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_event_id_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('riders_car_id_fkey', 'riders', type_='foreignkey')
    op.create_foreign_key(None, 'riders', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'riders', type_='foreignkey')
    op.create_foreign_key('riders_car_id_fkey', 'riders', 'cars', ['car_id'], ['id'])
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_event_id_fkey', 'cars', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
