"""empty message

Revision ID: 5b21149b4183
Revises: a59168767130
Create Date: 2019-03-11 16:56:01.601404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b21149b4183'
down_revision = 'a59168767130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('APIKey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APIKey',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='APIKey_pkey'),
    sa.UniqueConstraint('hash', name='APIKey_hash_key')
    )
    # ### end Alembic commands ###
