"""empty message

Revision ID: 7a38e879bb71
Revises: d50279c1f8aa
Create Date: 2020-05-07 21:28:02.999193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a38e879bb71'
down_revision = 'd50279c1f8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userteam', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userteam', 'is_admin')
    # ### end Alembic commands ###
