"""empty message

Revision ID: a59168767130
Revises: 0d4af7b34af9
Create Date: 2018-04-06 13:13:18.985218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59168767130'
down_revision = '0d4af7b34af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('departure_time', sa.DateTime(), nullable=False))
    op.add_column('cars', sa.Column('driver_comment', sa.Text(), nullable=True))
    op.add_column('cars', sa.Column('return_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'return_time')
    op.drop_column('cars', 'driver_comment')
    op.drop_column('cars', 'departure_time')
    # ### end Alembic commands ###
