"""empty message

Revision ID: bf24db157a79
Revises: 7a38e879bb71
Create Date: 2020-05-07 21:37:56.869137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf24db157a79'
down_revision = '7a38e879bb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('description', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'description')
    # ### end Alembic commands ###
