"""empty message

Revision ID: cf7a7f876d4c
Revises: e38761060575
Create Date: 2020-05-01 19:08:03.846340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7a7f876d4c'
down_revision = 'e38761060575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_bucket_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'bucket', ['bucket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('userbucket_bucket_id_fkey', 'userbucket', type_='foreignkey')
    op.create_foreign_key(None, 'userbucket', 'bucket', ['bucket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userbucket', type_='foreignkey')
    op.create_foreign_key('userbucket_bucket_id_fkey', 'userbucket', 'bucket', ['bucket_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_bucket_id_fkey', 'events', 'bucket', ['bucket_id'], ['id'])
    # ### end Alembic commands ###
