"""empty message

Revision ID: e38761060575
Revises: 991484de6914
Create Date: 2020-05-01 13:51:33.970482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38761060575'
down_revision = '991484de6914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bucket', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucket', type_='foreignkey')
    # ### end Alembic commands ###
